### ISSUE TITLE
Causes game to stutter

### ISSUE THREAD

**Issue by ghost** [artemiswkearney/HitScoreVisualizer#3]
When enabled this mod causes the game to stutter occasionally. Makes it unplayable as it throws you off as badly as when you accidentally hit pause.

It seems to happen when there are lots of notes on screen being chopped, thus producing lots of text. Playing OST1- Escape on Expert or Expert+ gives me stutters when the beat hits and you start chopping.

It's a shame as I like this mod!

System:
Vive
Windows 10
Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~3600 Mhz
16Gb ram
Nvidia Titan (Pascal)

**Comment by juliusfrost** [comment]
Can confirm

**Comment by artemiswkearney** [comment]
This is a result of the mod's normal functionality unavoidably requiring some amount of processing. Ultimately, every mod you use will consume some amount of system resources, so removing other mods may also help.  
Of note is that the "fade" config option increases the computational cost. Removing `"fade":true` from judgments in your config will increase performance.

That said, being reminded of this issue made me realize that there's actually something I might be able to do to optimize the plugin further. Looking into the possibility now.

**Comment by juliusfrost** [comment]
Thanks for the response!

**Comment by artemiswkearney** [comment]
Try the new version, with `"doIntermediateUpdates"` turned off?
