### ISSUE TITLE
Update to 1.15

### ISSUE THREAD

**Issue by Cobular** [artemiswkearney/HitScoreVisualizer#7]
Hey all, just wanted to point this out. I'll probably make a pr soonish to get this fixed.

**Comment by Dr-Turtle** [comment]
i assume u mean 1.5.0, it would be much appreciated if you make a pr for it

**Comment by Paolo-Paz** [comment]
Any update? I'd love to help if needed. I miss this mod more than any other mod!

**Comment by Dr-Turtle** [comment]
idk if it's still working, but I tried it for 1.5.0 in its current version and it worked.

**Comment by artemiswkearney** [comment]
Release v2.4.1 supports game version 1.5.0.
A beta is also available on BSMG that supports 1.6.0. A full release for 1.6.0 should be coming out soon.
